# Define the build version
version: 0.1.0.{build}

# Select the worker image
image: Visual Studio 2019

# Fake build script
build_script:
  - echo "This step would build the artifact in build-output/unsigned/combined.zip"
cache:
  - node_modules                    # local npm modules

#build_cloud: 'DESKTOP-U65200Q'
#image: Windows

# Definition of artifacts
artifacts:
  - path:  build-output\unsigned\combined test test.zip
# Set the signing policy slug according to branch
environment:
  SIGNPATH_ORGANIZATION_ID: 2cde3088-c473-4ca4-9c40-f5045412c616
  SIGNPATH_PROJECT_SLUG: AppVeyorTestProjectRobert
  SIGNPATH_SIGNING_POLICY_SLUG: AppVeyorTestProjectSigningPolicyRobert
  ARTIFACT_CONFIGURATION_SLUG: Default
  SIGNPATH_CI_USER_TOKEN:
    secure: upV2zFb3r2epww7+nBl8Ua2TY3T2NBeWQPtXKguPKfyVvE7xFOlSVKXBSCEUO2RX
deploy:
  - provider: Webhook
    url: http://appveyor-test.westeurope.cloudapp.azure.com/api/sign?OrganizationId=%SIGNPATH_ORGANIZATION_ID%&test=1&ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
    authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'
