# Define the build version
version: 0.1.0.{build}

# Select the worker image
image: Visual Studio 2019

# Fake build script
build_script:
  - echo "This step would build the artifact in build-output/unsigned/combined.zip"

# Definition of artifacts
artifacts:
  - path: build-output\unsigned\combined.zip

# Set the signing policy slug according to branch
environment:
  SIGNPATH_SIGNING_POLICY_SLUG: test-signing
  ARTIFACT_CONFIGURATION_SLUG: v1
for:
  -
    branches:
      only:
        - /release/.*/
        - master
    environment:
      SIGNPATH_SIGNING_POLICY_SLUG: release-signing

deploy:
  - provider: Webhook
    url: http://20.224.211.80/api/sign?OrganizationI1=%SIGNPATH_ORGANIZATION_ID%&test=1&ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
    authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'
