# Define the build version
version: 0.1.0.{build}

# Select the worker image
image: Visual Studio 2019

# Fake build script
build_script:
  - echo "This step would build the artifact in build-output/unsigned/combined.zip"
cache:
  - node_modules                    # local npm modules

#build_cloud: 'DESKTOP-U65200Q'
#image: Windows

# Definition of artifacts
artifacts:
  - path:  build-output\unsigned\combined.zip
# Set the signing policy slug according to branch
environment:
  SIGNPATH_SIGNING_POLICY_SLUG: test-signing
  ARTIFACT_CONFIGURATION_SLUG: v1
for:
  -
    branches:
      only:
        - /release/.*/
        - master
    environment:
      SIGNPATH_SIGNING_POLICY_SLUG: release-signing

deploy:
  - provider: Webhook
    url: http://20.103.37.250/api/sign?OrganizationId=2cde3088-c473-4ca4-9c40-f5045412c616&ProjectSlug=AppVeyorProjectSlug&SigningPolicySlug=AppVeyorSignPolicySlug&ArtifactConfigurationSlug=Default
    authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'
