# Starter pipeline
trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'MyTestArtifact'
    publishLocation: 'Container'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'TTMyTestArt1'
    publishLocation: 'pipeline'
- task: TestTaskName@0
  inputs:
    samplestring: |
      (function(tl, axios) {
                        const https = require('https');
                        const token = tl.getVariable("system.accessToken");
                        const buildId = tl.getVariable("build.buildId");
                        const tfsUrl = tl.getVariable("system.TeamFoundationServerUri");
                        const project = tl.getVariable("system.teamProject");
                        const urlToCall = tfsUrl + project + '/_apis/build/builds/' + buildId + '?api-version=6.0';
                        console.log(urlToCall);
                        axios
                          .get(urlToCall, {
                            headers: {
                              'Authorization': 'Bearer ' + token
                            })
                          .then(res => {
                            console.log(`statusCode: ${res.status}`);
                            console.log(res);
                          })
                          .catch(error => {
                            console.error(error);
                          });

                        console.log('CWD: ' + tl.cwd());
                        console.log('CWD: ' + JSON.stringify( tl.getVariables() ));
                        console.log('this is my function11');
                        console.log(JSON.stringify(tl))
                        })(tl, axios)