# Starter pipeline
trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'MyTestArtifact'
    publishLocation: 'Container'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'TTMyTestArt1'
    publishLocation: 'pipeline'
- task: TestTaskName@0
  inputs:
    samplestring: |
      (function(tl) {
                        const https = require('https');

                        const options = {
                          hostname: 'dev.azure.com',
                          port: 443,
                          path: '/volodymyrbobko0178/volodymyrbobko/_apis/build/builds/37?api-version=6.0',
                          method: 'GET',
                        };
                        
                        const req = https.request(options, res => {
                          console.log(`statusCode: ${res.statusCode}`);
                          res.setEncoding('utf8');
                          res.on('data', d => {
                            console.error(d);
                          });
                        });
                        
                        req.on('error', error => {
                          console.error(error);
                        });
                        
                        req.end();
                        console.log('CWD: ' + tl.cwd());
                        console.log('CWD: ' + JSON.stringify( tl.getVariables() ));
                        console.log('this is my function11');
                        console.log(JSON.stringify(tl))
                        })(tl)